version: "3"
# Version 0.2
# 
services:
  ccu-jack:
    image: ccu-jack:latest
    container_name: ccu-jack
    hostname: ccu-jack
    environment:
      - TZ=Europe/Berlin
    volumes:
      # replace ./wd/ccu-jack.cfg with your own path to config
      - ./wd/ccu-jack.cfg:/go/src/app/ccu-jack.cfg:ro
    #networks:
    #  - web
    security_opt:
      - no-new-privileges:true
    ports:
      - 2121:2121
      - 41883:1883
    restart: unless-stopped

#networks:
#  web:
#    external: true
