version: "3"
# Version 0.1: first working compose file
services:
  ccu-jack:
    image: ccu-jack:latest
    container_name: ccu-jack
    hostname: ccu-jack
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./wd/ccu-jack.cfg:/go/src/app/ccu-jack.cfg:ro
    networks:
      - web
    security_opt:
      - no-new-privileges:true
    ports:
      - 12121:2121
    restart: unless-stopped

networks:
  web:
    external: true
